name: Continuous Integration

on:
  push:
    tags:
      - "v[0-9]*"
    branches:
      - "**"

  pull_request:
    branches:
      - "**:**"

  schedule:
    - cron: "0 6 * * 1"

jobs:
  test:
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - uses: actions/checkout@v3
      - uses: crystal-lang/install-crystal@v1
      - run: shards install
      - run: make test

  test_mt:
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - uses: actions/checkout@v3
      - uses: crystal-lang/install-crystal@v1
      - run: shards install
      - run: make test CRFLAGS=-Dpreview_mt OPTS="--chaos --parallel=4"
